version: "2"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ../api:/api
      - ./server/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
      
  php:
    build: 
      context: .
      dockerfile: ./server/php/Dockerfile
    volumes:
      - ../api:/api
      - ./server/php/conf.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./server/php/conf.d/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
#      - ./server/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - code-network

  mongo:
    image: mongo:4.2
    restart: always
    command: --auth
    environment:
      MONGO_INITDB_DATABASE: rubrica
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: a
    ports:
      - "27017:27017"
    volumes:
      - ./server/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro  
      - ../../mongodata:/data/db  
    networks:
      - code-network

networks:
    code-network:
        driver: bridge