version: "1.0"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ../api:/var/www/html/
      - ./server/nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    image: php:7-fpm
    volumes:
        - ../api:/var/www/html/
      
