version: "2"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ../api:/api
      - ./server/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    image: php:fpm
    volumes:
      - ../api:/api
    networks:
      - code-network
  mongo:
    image: mongo:4.2
    restart: always
    command: --auth
    environment:
      MONGO_INITDB_DATABASE: rubrica
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: a
    ports:
      - "27017:27017"
    volumes:
      - ./server/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ../../mongodata:/data/db  

networks:
    code-network:
        driver: bridge